<?php
/**
 * Maps each hall slug -> array of stand info for that hall
 */

return [
    '3' => [
        [ 'id' => 'wv_hall_3_01', 'stand' => '3/01', 'label' => '' ],
        [ 'id' => 'wv_hall_3_02', 'stand' => '3/02', 'label' => '' ],
        [ 'id' => 'wv_hall_3_03', 'stand' => '3/03', 'label' => '' ],
        [ 'id' => 'wv_hall_3_04', 'stand' => '3/04', 'label' => '' ],
        [ 'id' => 'wv_hall_3_05', 'stand' => '3/05', 'label' => '' ],
        [ 'id' => 'wv_hall_3_06', 'stand' => '3/06', 'label' => '' ],
        [ 'id' => 'wv_hall_3_07', 'stand' => '3/07', 'label' => '' ],
        [ 'id' => 'wv_hall_3_08', 'stand' => '3/08', 'label' => '' ],
        [ 'id' => 'wv_hall_3_09', 'stand' => '3/09', 'label' => '' ],
        [ 'id' => 'wv_hall_3_10', 'stand' => '3/10', 'label' => '' ],
        [ 'id' => 'wv_hall_3_11', 'stand' => '3/11', 'label' => '' ],
        [ 'id' => 'wv_hall_3_12', 'stand' => '3/12', 'label' => '' ],
        [ 'id' => 'wv_hall_3_13', 'stand' => '3/13', 'label' => '' ],
        [ 'id' => 'wv_hall_3_14', 'stand' => '3/14', 'label' => '' ],
        [ 'id' => 'wv_hall_3_15', 'stand' => '3/15', 'label' => '' ],
        [ 'id' => 'wv_hall_3_16', 'stand' => '3/16', 'label' => '' ],
        [ 'id' => 'wv_hall_3_17', 'stand' => '3/17', 'label' => '' ],
        [ 'id' => 'wv_hall_3_18', 'stand' => '3/18', 'label' => '' ],
        [ 'id' => 'wv_hall_3_19', 'stand' => '3/19', 'label' => '' ],
        [ 'id' => 'wv_hall_3_20', 'stand' => '3/20', 'label' => '' ],
        [ 'id' => 'wv_hall_3_21', 'stand' => '3/21', 'label' => '' ],
        [ 'id' => 'wv_hall_3_22', 'stand' => '3/22', 'label' => '' ],
        [ 'id' => 'wv_hall_3_23', 'stand' => '3/23', 'label' => '' ],
        [ 'id' => 'wv_hall_3_24', 'stand' => '3/24', 'label' => '' ],
        [ 'id' => 'wv_hall_3_25', 'stand' => '3/25', 'label' => '' ],
        [ 'id' => 'wv_hall_3_26', 'stand' => '3/26', 'label' => '' ],
        [ 'id' => 'wv_hall_3_27', 'stand' => '3/27', 'label' => '' ],
        [ 'id' => 'wv_hall_3_28', 'stand' => '3/28', 'label' => '' ],
        [ 'id' => 'wv_hall_3_29', 'stand' => '3/29', 'label' => '' ],
        [ 'id' => 'wv_hall_3_30', 'stand' => '3/30', 'label' => '' ],
        [ 'id' => 'wv_hall_3_31', 'stand' => '3/31', 'label' => '' ],
        [ 'id' => 'wv_hall_3_32', 'stand' => '3/32', 'label' => '' ],
        [ 'id' => 'wv_hall_3_33', 'stand' => '3/33', 'label' => '' ],
        [ 'id' => 'wv_hall_3_34', 'stand' => '3/34', 'label' => '' ],
        [ 'id' => 'wv_hall_3_35', 'stand' => '3/35', 'label' => '' ],
        [ 'id' => 'wv_hall_3_36', 'stand' => '3/36', 'label' => '' ],
        [ 'id' => 'wv_hall_3_37', 'stand' => '3/37', 'label' => '' ],
        [ 'id' => 'wv_hall_3_38', 'stand' => '3/38', 'label' => '' ],
        [ 'id' => 'wv_hall_3_39', 'stand' => '3/39', 'label' => '' ],
        [ 'id' => 'wv_hall_3_40', 'stand' => '3/40', 'label' => '' ],
        [ 'id' => 'wv_hall_3_41', 'stand' => '3/41', 'label' => '' ],
        [ 'id' => 'wv_hall_3_42', 'stand' => '3/42', 'label' => '' ],
        [ 'id' => 'wv_hall_3_43', 'stand' => '3/43', 'label' => '' ],
        [ 'id' => 'wv_hall_3_44', 'stand' => '3/44', 'label' => '' ],
        [ 'id' => 'wv_hall_3_45', 'stand' => '3/45', 'label' => '' ],
        [ 'id' => 'wv_hall_3_46', 'stand' => '3/46', 'label' => '' ],
    ],
    '3A' => [
        [ 'id' => 'wv_hall_3A_01', 'stand' => '3A/01', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_02', 'stand' => '3A/02', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_03', 'stand' => '3A/03', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_04', 'stand' => '3A/04', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_05', 'stand' => '3A/05', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_06', 'stand' => '3A/06', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_07', 'stand' => '3A/07', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_08', 'stand' => '3A/08', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_09', 'stand' => '3A/09', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_10', 'stand' => '3A/10', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_11', 'stand' => '3A/11', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_12', 'stand' => '3A/12', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_13', 'stand' => '3A/13', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_14', 'stand' => '3A/14', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_15', 'stand' => '3A/15', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_16', 'stand' => '3A/16', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_17', 'stand' => '3A/17', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_18', 'stand' => '3A/18', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_19', 'stand' => '3A/19', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_20', 'stand' => '3A/20', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_21', 'stand' => '3A/21', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_22', 'stand' => '3A/22', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_23', 'stand' => '3A/23', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_24', 'stand' => '3A/24', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_25', 'stand' => '3A/25', 'label' => '' ],
        [ 'id' => 'wv_hall_3A_26', 'stand' => '3A/26', 'label' => '' ],
    ],
    '2B' => [
        [ 'id' => 'wv_hall_2B_01', 'stand' => '2B/01', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_02', 'stand' => '2B/02', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_03', 'stand' => '2B/03', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_04', 'stand' => '2B/04', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_05', 'stand' => '2B/05', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_06', 'stand' => '2B/06', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_07', 'stand' => '2B/07', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_08', 'stand' => '2B/08', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_09', 'stand' => '2B/09', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_10', 'stand' => '2B/10', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_11', 'stand' => '2B/11', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_12', 'stand' => '2B/12', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_13', 'stand' => '2B/13', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_14', 'stand' => '2B/14', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_15', 'stand' => '2B/15', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_16', 'stand' => '2B/16', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_17', 'stand' => '2B/17', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_18', 'stand' => '2B/18', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_19', 'stand' => '2B/19', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_20', 'stand' => '2B/20', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_21', 'stand' => '2B/21', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_22', 'stand' => '2B/22', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_23', 'stand' => '2B/23', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_24', 'stand' => '2B/24', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_25', 'stand' => '2B/25', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_26', 'stand' => '2B/26', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_27', 'stand' => '2B/27', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_28', 'stand' => '2B/28', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_29', 'stand' => '2B/29', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_30', 'stand' => '2B/30', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_31', 'stand' => '2B/31', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_32', 'stand' => '2B/32', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_33', 'stand' => '2B/33', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_34', 'stand' => '2B/34', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_35', 'stand' => '2B/35', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_36', 'stand' => '2B/36', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_37', 'stand' => '2B/37', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_38', 'stand' => '2B/38', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_39', 'stand' => '2B/39', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_40', 'stand' => '2B/40', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_41', 'stand' => '2B/41', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_42', 'stand' => '2B/42', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_43', 'stand' => '2B/43', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_44', 'stand' => '2B/44', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_45', 'stand' => '2B/45', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_46', 'stand' => '2B/46', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_47', 'stand' => '2B/47', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_48', 'stand' => '2B/48', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_49', 'stand' => '2B/49', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_50', 'stand' => '2B/50', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_51', 'stand' => '2B/51', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_52', 'stand' => '2B/52', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_53', 'stand' => '2B/53', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_54', 'stand' => '2B/54', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_55', 'stand' => '2B/55', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_56', 'stand' => '2B/56', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_57', 'stand' => '2B/57', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_58', 'stand' => '2B/58', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_59', 'stand' => '2B/59', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_60', 'stand' => '2B/60', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_61', 'stand' => '2B/61', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_62', 'stand' => '2B/62', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_63', 'stand' => '2B/63', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_64', 'stand' => '2B/64', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_65', 'stand' => '2B/65', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_66', 'stand' => '2B/66', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_67', 'stand' => '2B/67', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_68', 'stand' => '2B/68', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_69', 'stand' => '2B/69', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_70', 'stand' => '2B/70', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_71', 'stand' => '2B/71', 'label' => '' ],
        [ 'id' => 'wv_hall_2B_72', 'stand' => '2B/72', 'label' => '' ],
        
    ],
    '2A' => [
        [ 'id' => 'wv_hall_2A_01', 'stand' => '2A/01', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_02', 'stand' => '2A/02', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_03', 'stand' => '2A/03', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_04', 'stand' => '2A/04', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_05', 'stand' => '2A/05', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_06', 'stand' => '2A/06', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_07', 'stand' => '2A/07', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_08', 'stand' => '2A/08', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_09', 'stand' => '2A/09', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_10', 'stand' => '2A/10', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_11', 'stand' => '2A/11', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_12', 'stand' => '2A/12', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_13', 'stand' => '2A/13', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_14', 'stand' => '2A/14', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_15', 'stand' => '2A/15', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_16', 'stand' => '2A/16', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_17', 'stand' => '2A/17', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_18', 'stand' => '2A/18', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_19', 'stand' => '2A/19', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_20', 'stand' => '2A/20', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_21', 'stand' => '2A/21', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_22', 'stand' => '2A/22', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_23', 'stand' => '2A/23', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_24', 'stand' => '2A/24', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_25', 'stand' => '2A/25', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_26', 'stand' => '2A/26', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_27', 'stand' => '2A/27', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_28', 'stand' => '2A/28', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_29', 'stand' => '2A/29', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_30', 'stand' => '2A/30', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_31', 'stand' => '2A/31', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_32', 'stand' => '2A/32', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_33', 'stand' => '2A/33', 'label' => '' ],
        [ 'id' => 'wv_hall_2A_34', 'stand' => '2A/34', 'label' => '' ],
    ],
    '2C' => [
        [ 'id' => 'wv_hall_2C_01', 'stand' => '2C/01', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_02', 'stand' => '2C/02', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_03', 'stand' => '2C/03', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_04', 'stand' => '2C/04', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_05', 'stand' => '2C/05', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_06', 'stand' => '2C/06', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_07', 'stand' => '2C/07', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_08', 'stand' => '2C/08', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_09', 'stand' => '2C/09', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_10', 'stand' => '2C/10', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_11', 'stand' => '2C/11', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_12', 'stand' => '2C/12', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_13', 'stand' => '2C/13', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_14', 'stand' => '2C/14', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_15', 'stand' => '2C/15', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_16', 'stand' => '2C/16', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_17', 'stand' => '2C/17', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_18', 'stand' => '2C/18', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_19', 'stand' => '2C/19', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_20', 'stand' => '2C/20', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_21', 'stand' => '2C/21', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_22', 'stand' => '2C/22', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_23', 'stand' => '2C/23', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_24', 'stand' => '2C/24', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_25', 'stand' => '2C/25', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_26', 'stand' => '2C/26', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_27', 'stand' => '2C/27', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_28', 'stand' => '2C/28', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_29', 'stand' => '2C/29', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_30', 'stand' => '2C/30', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_31', 'stand' => '2C/31', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_32', 'stand' => '2C/32', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_33', 'stand' => '2C/33', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_34', 'stand' => '2C/34', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_35', 'stand' => '2C/35', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_36', 'stand' => '2C/36', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_37', 'stand' => '2C/37', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_38', 'stand' => '2C/38', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_39', 'stand' => '2C/39', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_40', 'stand' => '2C/40', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_41', 'stand' => '2C/41', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_42', 'stand' => '2C/42', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_43', 'stand' => '2C/43', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_44', 'stand' => '2C/44', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_45', 'stand' => '2C/45', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_46', 'stand' => '2C/46', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_47', 'stand' => '2C/47', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_48', 'stand' => '2C/48', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_49', 'stand' => '2C/49', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_50', 'stand' => '2C/50', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_51', 'stand' => '2C/51', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_52', 'stand' => '2C/52', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_53', 'stand' => '2C/53', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_54', 'stand' => '2C/54', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_55', 'stand' => '2C/55', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_56', 'stand' => '2C/56', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_57', 'stand' => '2C/57', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_58', 'stand' => '2C/58', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_59', 'stand' => '2C/59', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_60', 'stand' => '2C/60', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_61', 'stand' => '2C/61', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_62', 'stand' => '2C/62', 'label' => '' ],
        [ 'id' => 'wv_hall_2C_63', 'stand' => '2C/63', 'label' => '' ],
    ],    
    '1A'  => [
        [ 'id' => 'wv_hall_1A_01', 'stand' => '1A/01', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_02', 'stand' => '1A/02', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_03', 'stand' => '1A/03', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_04', 'stand' => '1A/04', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_05', 'stand' => '1A/05', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_06', 'stand' => '1A/06', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_07', 'stand' => '1A/07', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_08', 'stand' => '1A/08', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_09', 'stand' => '1A/09', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_10', 'stand' => '1A/10', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_11', 'stand' => '1A/11', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_12', 'stand' => '1A/12', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_13', 'stand' => '1A/13', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_14', 'stand' => '1A/14', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_15', 'stand' => '1A/15', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_16', 'stand' => '1A/16', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_17', 'stand' => '1A/17', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_18', 'stand' => '1A/18', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_19', 'stand' => '1A/19', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_20', 'stand' => '1A/20', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_21', 'stand' => '1A/21', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_22', 'stand' => '1A/22', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_23', 'stand' => '1A/23', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_24', 'stand' => '1A/24', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_25', 'stand' => '1A/25', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_26', 'stand' => '1A/26', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_27', 'stand' => '1A/27', 'label' => '' ],
        [ 'id' => 'wv_hall_1A_28', 'stand' => '1A/28', 'label' => '' ],
    ],
    '1' => [
        [ 'id' => 'wv_hall_1_01', 'stand' => '1/01', 'label' => 'Antic Winery' ],
        [ 'id' => 'wv_hall_1_02', 'stand' => '1/02', 'label' => 'Bahus Winery' ],
        [ 'id' => 'wv_hall_1_03', 'stand' => '1/03', 'label' => 'Winery 03' ],
        [ 'id' => 'wv_hall_1_04', 'stand' => '1/04', 'label' => 'Winery 04' ],
        [ 'id' => 'wv_hall_1_05', 'stand' => '1/05', 'label' => 'Winery 05' ],
        [ 'id' => 'wv_hall_1_06', 'stand' => '1/06', 'label' => 'Winery 06' ],
        [ 'id' => 'wv_hall_1_07', 'stand' => '1/07', 'label' => 'Winery 07' ],
        [ 'id' => 'wv_hall_1_08', 'stand' => '1/08', 'label' => 'Winery 08' ],
        [ 'id' => 'wv_hall_1_09', 'stand' => '1/09', 'label' => 'Winery 09' ],
        [ 'id' => 'wv_hall_1_10', 'stand' => '1/10', 'label' => 'Winery 10' ],
        [ 'id' => 'wv_hall_1_11', 'stand' => '1/11', 'label' => 'Winery 11' ],
        [ 'id' => 'wv_hall_1_12', 'stand' => '1/12', 'label' => 'Winery 12' ],
        [ 'id' => 'wv_hall_1_13', 'stand' => '1/13', 'label' => 'Winery 13' ],
        [ 'id' => 'wv_hall_1_14', 'stand' => '1/14', 'label' => 'Winery 14' ],
        [ 'id' => 'wv_hall_1_15', 'stand' => '1/15', 'label' => 'Winery 15' ],
        [ 'id' => 'wv_hall_1_16', 'stand' => '1/16', 'label' => 'Winery 16' ],
        [ 'id' => 'wv_hall_1_17', 'stand' => '1/17', 'label' => 'Winery 17' ],
        [ 'id' => 'wv_hall_1_18', 'stand' => '1/18', 'label' => 'Winery 18' ],
        [ 'id' => 'wv_hall_1_19', 'stand' => '1/19', 'label' => 'Winery 19' ],
        [ 'id' => 'wv_hall_1_20', 'stand' => '1/20', 'label' => 'Winery 20' ],
        [ 'id' => 'wv_hall_1_21', 'stand' => '1/21', 'label' => 'Winery 21' ],
        [ 'id' => 'wv_hall_1_22', 'stand' => '1/22', 'label' => 'Winery 22' ],
        [ 'id' => 'wv_hall_1_23', 'stand' => '1/23', 'label' => 'Winery 23' ],
        [ 'id' => 'wv_hall_1_24', 'stand' => '1/24', 'label' => 'Winery 24' ],
        [ 'id' => 'wv_hall_1_25', 'stand' => '1/25', 'label' => 'Winery 25' ],
        [ 'id' => 'wv_hall_1_26', 'stand' => '1/26', 'label' => 'Winery 26' ],
        [ 'id' => 'wv_hall_1_27', 'stand' => '1/27', 'label' => 'Winery 27' ],
        [ 'id' => 'wv_hall_1_28', 'stand' => '1/28', 'label' => 'Winery 28' ],
        [ 'id' => 'wv_hall_1_29', 'stand' => '1/29', 'label' => 'Winery 29' ],
        [ 'id' => 'wv_hall_1_30', 'stand' => '1/30', 'label' => 'Winery 30' ],
        [ 'id' => 'wv_hall_1_31', 'stand' => '1/31', 'label' => 'Winery 31' ],
        [ 'id' => 'wv_hall_1_32', 'stand' => '1/32', 'label' => 'Winery 32' ],
        [ 'id' => 'wv_hall_1_33', 'stand' => '1/33', 'label' => 'Winery 33' ],
        [ 'id' => 'wv_hall_1_34', 'stand' => '1/34', 'label' => 'Winery 34' ],
        [ 'id' => 'wv_hall_1_35', 'stand' => '1/35', 'label' => 'Winery 35' ],
        [ 'id' => 'wv_hall_1_36', 'stand' => '1/36', 'label' => 'Winery 36' ],
        [ 'id' => 'wv_hall_1_37', 'stand' => '1/37', 'label' => 'Winery 37' ],
        [ 'id' => 'wv_hall_1_38', 'stand' => '1/38', 'label' => 'Winery 38' ],
        [ 'id' => 'wv_hall_1_39', 'stand' => '1/39', 'label' => 'Winery 39' ],
        [ 'id' => 'wv_hall_1_40', 'stand' => '1/40', 'label' => 'Winery 40' ],
        [ 'id' => 'wv_hall_1_41', 'stand' => '1/41', 'label' => 'Winery 41' ],
        [ 'id' => 'wv_hall_1_42', 'stand' => '1/42', 'label' => 'Winery 42' ],
        [ 'id' => 'wv_hall_1_43', 'stand' => '1/43', 'label' => 'Winery 43' ],
        [ 'id' => 'wv_hall_1_44', 'stand' => '1/44', 'label' => 'Winery 44' ],
        [ 'id' => 'wv_hall_1_45', 'stand' => '1/45', 'label' => 'Winery 45' ],
        [ 'id' => 'wv_hall_1_46', 'stand' => '1/46', 'label' => 'Winery 46' ],
        [ 'id' => 'wv_hall_1_47', 'stand' => '1/47', 'label' => 'Winery 47' ],
        [ 'id' => 'wv_hall_1_48', 'stand' => '1/48', 'label' => 'Winery 48' ],
        [ 'id' => 'wv_hall_1_49', 'stand' => '1/49', 'label' => 'Winery 49' ],
        [ 'id' => 'wv_hall_1_50', 'stand' => '1/50', 'label' => 'Winery 50' ],
        [ 'id' => 'wv_hall_1_51', 'stand' => '1/51', 'label' => 'Winery 51' ],
        [ 'id' => 'wv_hall_1_52', 'stand' => '1/52', 'label' => 'Winery 52' ],
        [ 'id' => 'wv_hall_1_53', 'stand' => '1/53', 'label' => 'Winery 53' ],
        [ 'id' => 'wv_hall_1_54', 'stand' => '1/54', 'label' => 'Winery 54' ],
        [ 'id' => 'wv_hall_1_55', 'stand' => '1/55', 'label' => 'Winery 55' ],
        [ 'id' => 'wv_hall_1_56', 'stand' => '1/56', 'label' => 'Winery 56' ],
        [ 'id' => 'wv_hall_1_57', 'stand' => '1/57', 'label' => 'Winery 57' ],
        [ 'id' => 'wv_hall_1_58', 'stand' => '1/58', 'label' => 'Winery 58' ],
        [ 'id' => 'wv_hall_1_59', 'stand' => '1/59', 'label' => 'Winery 59' ],
        [ 'id' => 'wv_hall_1_60', 'stand' => '1/60', 'label' => 'Winery 60' ],
        [ 'id' => 'wv_hall_1_61', 'stand' => '1/61', 'label' => 'Winery 61' ],
        [ 'id' => 'wv_hall_1_62', 'stand' => '1/62', 'label' => 'Winery 62' ],
        [ 'id' => 'wv_hall_1_63', 'stand' => '1/63', 'label' => 'Winery 63' ],
    ],
    '1G' => [
        [ 'id' => 'wv_hall_1G_01', 'stand' => '1G/01', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_02', 'stand' => '1G/02', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_03', 'stand' => '1G/03', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_04', 'stand' => '1G/04', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_05', 'stand' => '1G/05', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_06', 'stand' => '1G/06', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_07', 'stand' => '1G/07', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_08', 'stand' => '1G/08', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_09', 'stand' => '1G/09', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_10', 'stand' => '1G/10', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_11', 'stand' => '1G/11', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_12', 'stand' => '1G/12', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_13', 'stand' => '1G/13', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_14', 'stand' => '1G/14', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_15', 'stand' => '1G/15', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_16', 'stand' => '1G/16', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_17', 'stand' => '1G/17', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_18', 'stand' => '1G/18', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_19', 'stand' => '1G/19', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_20', 'stand' => '1G/20', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_21', 'stand' => '1G/21', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_22', 'stand' => '1G/22', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_23', 'stand' => '1G/23', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_24', 'stand' => '1G/24', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_25', 'stand' => '1G/25', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_26', 'stand' => '1G/26', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_27', 'stand' => '1G/27', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_28', 'stand' => '1G/28', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_29', 'stand' => '1G/29', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_30', 'stand' => '1G/30', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_31', 'stand' => '1G/31', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_32', 'stand' => '1G/32', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_33', 'stand' => '1G/33', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_34', 'stand' => '1G/34', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_35', 'stand' => '1G/35', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_36', 'stand' => '1G/36', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_37', 'stand' => '1G/37', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_38', 'stand' => '1G/38', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_39', 'stand' => '1G/39', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_40', 'stand' => '1G/40', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_41', 'stand' => '1G/41', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_42', 'stand' => '1G/42', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_43', 'stand' => '1G/43', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_44', 'stand' => '1G/44', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_45', 'stand' => '1G/45', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_46', 'stand' => '1G/46', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_47', 'stand' => '1G/47', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_48', 'stand' => '1G/48', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_49', 'stand' => '1G/49', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_50', 'stand' => '1G/50', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_51', 'stand' => '1G/51', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_52', 'stand' => '1G/52', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_53', 'stand' => '1G/53', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_54', 'stand' => '1G/54', 'label' => '' ],
        [ 'id' => 'wv_hall_1G_55', 'stand' => '1G/55', 'label' => '' ],
    ],
    '4A' => [
        [ 'id' => 'wv_hall_4A_01', 'stand' => '4A/01', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_02', 'stand' => '4A/02', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_03', 'stand' => '4A/03', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_04', 'stand' => '4A/04', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_05', 'stand' => '4A/05', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_06', 'stand' => '4A/06', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_07', 'stand' => '4A/07', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_08', 'stand' => '4A/08', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_09', 'stand' => '4A/09', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_10', 'stand' => '4A/10', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_11', 'stand' => '4A/11', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_12', 'stand' => '4A/12', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_13', 'stand' => '4A/13', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_14', 'stand' => '4A/14', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_15', 'stand' => '4A/15', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_16', 'stand' => '4A/16', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_17', 'stand' => '4A/17', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_18', 'stand' => '4A/18', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_19', 'stand' => '4A/19', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_20', 'stand' => '4A/20', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_21', 'stand' => '4A/21', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_22', 'stand' => '4A/22', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_23', 'stand' => '4A/23', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_24', 'stand' => '4A/24', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_25', 'stand' => '4A/25', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_26', 'stand' => '4A/26', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_27', 'stand' => '4A/27', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_28', 'stand' => '4A/28', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_29', 'stand' => '4A/29', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_30', 'stand' => '4A/30', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_31', 'stand' => '4A/31', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_32', 'stand' => '4A/32', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_33', 'stand' => '4A/33', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_34', 'stand' => '4A/34', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_35', 'stand' => '4A/35', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_36', 'stand' => '4A/36', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_37', 'stand' => '4A/37', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_38', 'stand' => '4A/38', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_39', 'stand' => '4A/39', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_40', 'stand' => '4A/40', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_41', 'stand' => '4A/41', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_42', 'stand' => '4A/42', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_43', 'stand' => '4A/43', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_44', 'stand' => '4A/44', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_45', 'stand' => '4A/45', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_46', 'stand' => '4A/46', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_47', 'stand' => '4A/47', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_48', 'stand' => '4A/48', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_49', 'stand' => '4A/49', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_50', 'stand' => '4A/50', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_51', 'stand' => '4A/51', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_52', 'stand' => '4A/52', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_53', 'stand' => '4A/53', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_54', 'stand' => '4A/54', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_55', 'stand' => '4A/55', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_56', 'stand' => '4A/56', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_57', 'stand' => '4A/57', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_58', 'stand' => '4A/58', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_59', 'stand' => '4A/59', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_60', 'stand' => '4A/60', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_61', 'stand' => '4A/61', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_62', 'stand' => '4A/62', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_63', 'stand' => '4A/63', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_64', 'stand' => '4A/64', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_65', 'stand' => '4A/65', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_66', 'stand' => '4A/66', 'label' => '' ],
        [ 'id' => 'wv_hall_4A_67', 'stand' => '4A/67', 'label' => '' ],
    ],
    '4B' => [],
];
